### ISSUE TITLE
Mir Solar Panels not drawing any power

### ISSUE THREAD

**Issue by Toa-Sampa** [zer0Kerbal/MIR#58]
Noticed problem when launching Kvant 2, which had the Mir Solar Panels installed.  I extended the panels alright, and it appears to not be exposed, despite having direct sunlight on the panels, and not generating any power whatsoever!  I am using TAC Life Support so, it might be conflicting?  Will remove the mod, after I land my current crew, to see if I get any power back.

**Comment by Toa-Sampa** [comment]
Also, the sun tracking appears to not be working

**Comment by zer0Kerbal** [comment]
@Toa-Sampa apologies - my 🧠 oozed out of my head about twenty minutes ago - been pushing hard to modernize 99 parts for BAE - and almost have it - just need to make sure everything shows up. BAE has the same issue --- I know it is the part.config solar module - just need to find where I had fixed it before... maybe LazTek?

**Comment by Toa-Sampa** [comment]
no problem.  I was able to find out that TAC had nothing to do with the problem

**Comment by zer0Kerbal** [comment]
https://github.com/zer0Kerbal/MIR/blob/6dc291e270eb6215f6666948c977ba36e22504e9/GameData/BobCat/SovietPack/MIR/Parts/mir-kvant-solar.cfg#L48
	MODULE
	{
		name = ModuleDeployableSolarPanel
		animationName = kvant_solar
		secondaryTransformName = suncatcher
		// raycastTransformName = sunAR
		resourceName = ElectricCharge
		chargeRate = 10
		impactResistance = 2
		impactResistanceRetracted = 6
		extendActionName = #autoLOC_6001805 //#autoLOC_6001805 = Extend <<1>>
		retractActionName = #autoLOC_6001806 //#autoLOC_6001806 = Retract <<1>>
		extendpanelsActionName = #autoLOC_6001807 //#autoLOC_6001807 = Toggle <<1>>
		// sunTracking = false
		pivotName = sunPivot
		// powerCurve
		// {
		// 	key = 206000000000 0 0 0
		// 	key = 13599840256 1 0 0
		// 	key = 68773560320 0.5 0 0
		// 	key = 0 10 0 0
		// }
	}

https://github.com/zer0Kerbal/HistoricArchive/blob/7ea005ff36f35b30ddc2af7aecb0b674c55ac47f/GameData/LazTek/HistoricArchive/Parts/lha-solar-mini.cfg#L47
	MODULE
	{
		name = ModuleDeployableSolarPanel
		animationName = Take 001
		// raycastTransformName = suncatcher
		resourceName = ElectricCharge
		chargeRate = 8
		impactResistance = 2
		impactResistanceRetracted = 6
		extendActionName = #autoLOC_6001805 //#autoLOC_6001805 = Extend <<1>>
		retractActionName = #autoLOC_6001806 //#autoLOC_6001806 = Retract <<1>>
		extendpanelsActionName = #autoLOC_6001807 //#autoLOC_6001807 = Toggle <<1>>
		// powerCurve
		// {
		// 	key = 206000000000 0 0 0
		// 	key = 13599840256 1 0 0
		// 	key = 68773560320 0.5 0 0
		// 	key = 0 10 0 0
		// }
	}

**Comment by zer0Kerbal** [comment]
@Toa-Sampa this might work:
```
	MODULE
	{
		name = ModuleDeployableSolarPanel
		animationName = kvant_solar
		impactResistance = 2
		impactResistanceRetracted = 6
		resourceName = ElectricCharge
		chargeRate = 10
		extendActionName = #autoLOC_6001805 //#autoLOC_6001805 = Extend <<1>>
		retractActionName = #autoLOC_6001806 //#autoLOC_6001806 = Retract <<1>>
		extendpanelsActionName = #autoLOC_6001807 //#autoLOC_6001807 = Toggle <<1>>
	}
```

**Comment by Toa-Sampa** [comment]
I will test that soon.  while at it, take a look at the primary Mir Solar Panels (the ones that would launch aboard the Mir Core and all the other modules, excluding Zarya)

**Comment by zer0Kerbal** [comment]
thank you - fixing one should lead to the fix fir all.
